### ISSUE TITLE
Time string in file name causing issue in Windows.

### ISSUE THREAD

**Issue by dipanghosh** [wjh18/pyspeedinsights#4]
`(base) C:\Users\Dipan>psi https://dipan.pages.dev
Preparing 1 URL(s)...
Sending request... (https://dipan.pages.dev)
Request successful! (https://dipan.pages.dev)
1/1 URL(s) processed successfully.
Traceback (most recent call last):
  File "c:\users\dipan\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dipan\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dipan\miniconda3\Scripts\psi.exe\__main__.py", line 7, in <module>
  File "c:\users\dipan\miniconda3\lib\site-packages\pyspeedinsights\app.py", line 62, in main
    process_json(response, category, strategy)
  File "c:\users\dipan\miniconda3\lib\site-packages\pyspeedinsights\api\response.py", line 14, in process_json
    with open(filename, "w", encoding="utf-8") as f:
OSError: [Errno 22] Invalid argument: 'psi-s-desktop-c-performance-2022-10-27 11:05:25.626000.json'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022D4D691820>
Traceback (most recent call last):
  File "c:\users\dipan\miniconda3\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "c:\users\dipan\miniconda3\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\users\dipan\miniconda3\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "c:\users\dipan\miniconda3\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`

We get this traceback in Windows. The filename is not vaild.

**Comment by wjh18** [comment]
Thanks for reporting. Looks like the issue is with how the timestamp is created with `_get_timestamp()` in the `api.response` module. Colons are invalid characters in filenames on Windows. I will find a more suitable way to convert the UTC timestamp for use in the filename.

**Comment by dipanghosh** [comment]
Yes, I noticed the issue in the source code. Thanks for taking care of the issue.

Nice library, it works otherwise, there are some kinks to sort out.

**Comment by wjh18** [comment]
That should resolve it. If you run into any issues let me know.

And thank you. I'm glad it's been useful. I plan to add test coverage soon and take a look at some options for keyring fallback as you mentioned. I'm still figuring things out as this is my first package release 😃
