### ISSUE TITLE
Keyring in Linux causing problem

### ISSUE THREAD

**Issue by dipanghosh** [wjh18/pyspeedinsights#5]
This is not entirely a problem of pyspeedinsights, but hard dependency on keyrings is leading to problems in Linux. Keyrings have a [known issue](https://github.com/jaraco/keyring/issues/413) in Linux and therefore this cannot be used in Linux. 

A method for directly supplying the api-key would be preferrable.

**Comment by wjh18** [comment]
I believe keyring works on Linux but requires some manual config of the backend.

Are you opposed to being prompted for the key before every run if keyring fails to find a key? Or is that too much of a hinderance on your workflow? If automation is involved that may not be ideal.

I'm trying to think of an equally secure way to persist the key over multiple runs. Using environment variables might be sufficient but I'll have to do some research.

**Comment by dipanghosh** [comment]
`>> psi https://dipan.pages.dev
Preparing 1 URL(s)...
Traceback (most recent call last):
  File "/home2/dipan.ghosh/.local/bin/psi", line 8, in <module>
    sys.exit(main())
  File "/home2/dipan.ghosh/.local/lib/python3.10/site-packages/pyspeedinsights/app.py", line 52, in main
    responses = asyncio.run(gather_responses(request_urls, api_args_dict))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home2/dipan.ghosh/.local/lib/python3.10/site-packages/pyspeedinsights/api/request.py", line 78, in gather_responses
    responses = await asyncio.gather(*tasks)
  File "/home2/dipan.ghosh/.local/lib/python3.10/site-packages/pyspeedinsights/api/request.py", line 40, in get_response
    params["key"] = get_api_key()
  File "/home2/dipan.ghosh/.local/lib/python3.10/site-packages/pyspeedinsights/api/keys.py", line 11, in get_api_key
    PSI_API_KEY = keyring.get_password("system", "psikey")
  File "/home2/dipan.ghosh/.local/lib/python3.10/site-packages/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/home2/dipan.ghosh/.local/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
  File "/home2/dipan.ghosh/.local/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 67, in get_preferred_collection
    raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!`


I am getting this traceback on Linux. Yes, it is true that I can get Keyring to work by configuring it. I believe the prompt for key only works if the collection can be unlocked and the key cannot be found. Here, the collection itself cannot be accessed by keyring and the key fails. It should ask the user to provide the api key instead.

**Comment by wjh18** [comment]
Also done - I ran a quick test on MacOS by disabling access to the keychain password. The exception is handled with the base `KeyringError` so it should catch any keyring-specific exceptions and prompt for a fallback key.
